name: Build and Test and Deploy

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*

env:
  PROJECT_ID: cd-api-387508 # TODO: update Google Cloud project id
  SERVICE: tasks-api # TODO: update Cloud Run service name
  REGION: australia-southeast2 # TODO: update Cloud Run service region

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 18

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
